---
# sudo ansible-playbook migration-playbook.yml -i inventory.yml
- name: Standard Setup
  hosts: all
  become: yes
  vars:
    tenant: "NULL"
    user: "NULL"
    secret: "NULL"

  tasks:
  - name: Update VM
    ansible.builtin.apt:
      name: '*'
      state: latest
      update_cache: true
  - name: Install docker
    ansible.builtin.apt:
        pkg:
          - docker
          - docker-compose
          - docker-registry
          - docker.io
          - jq
  - name: Download and install Azure CLI
    ansible.builtin.shell:
      cmd: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - name: Login in to Azure CLI
    ansible.builtin.shell:
      cmd: "az login --service-principal -u {{ user }} -p {{ secret }} --tenant {{ tenant }}"
  - name: Save env variables
    ansible.builtin.shell:
      cmd: export ZEPHYR_API_TOKEN=$(az keyvault secret show --name ZEPHYR_API_TOKEN --vault-name ejoexamkeyvault | jq -r '.value')
      cmd: export AZURE_API_TOKEN=$(az keyvault secret show --name AZURE_API_TOKEN --vault-name ejoexamkeyvault | jq -r '.value')
      cmd: export AZURE_ORGANISATION=$(az keyvault secret show --name AZURE_ORGANISATION --vault-name ejoexamkeyvault | jq -r '.value')
      cmd: export JIRA_ACCOUNT_EMAIL=$(az keyvault secret show --name JIRA_ACCOUNT_EMAIL --vault-name ejoexamkeyvault | jq -r '.value')
      cmd: export JIRA_API_TOKEN=$(az keyvault secret show --name JIRA_API_TOKEN --vault-name ejoexamkeyvault | jq -r '.value')
      cmd: export JIRA_DOMAIN=$(az keyvault secret show --name JIRA_DOMAIN --vault-name ejoexamkeyvault | jq -r '.value')
  - name: Run Migration
    ansible.builtin.shell:
      cmd: docker run -it --env-file /path/to/env --rm ghcr.io/solidify-internal/jtmm:latest -p zephyr -s 10006 -t N7