name: Test docker image and deploy
run-name: ${{ github.actor }} pushed 
on: [push]


jobs:
  login_to_registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.EJO_GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}


  deploy_migration:
      runs-on: ubuntu-latest

      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }} 
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      steps:
        - run: echo Testing
        - run: az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        - run: sudo apt-get update && sudo apt-get install -y gnupg software-properties-common 
        - run: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        - run: gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
        - run: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        - run: sudo apt update
        - run: sudo apt-get install terraform
        - name: checkout repo
          uses: actions/checkout@v2.3.4
        - run: terraform init
        - run: terraform apply -auto-approve
        - run: az keyvault secret set --name ZEPHYR_API_TOKEN --vault-name ejoexamkeyvault --value ${{ secrets.ZEPHYR_API_TOKEN }} 
        - run: az keyvault secret set --name AZURE_API_TOKEN --vault-name ejoexamkeyvault --value ${{ secrets.AZURE_API_TOKEN }} 
        - run: az keyvault secret set --name AZURE_ORGANISATION --vault-name ejoexamkeyvault --value ${{ secrets.AZURE_ORGANISATION }} 
        - run: az keyvault secret set --name JIRA_ACCOUNT_EMAIL --vault-name ejoexamkeyvault --value ${{ secrets.JIRA_ACCOUNT_EMAIL }} 
        - run: az keyvault secret set --name JIRA_API_TOKEN --vault-name ejoexamkeyvault --value ${{ secrets.JIRA_API_TOKEN }} 
        - run: az keyvault secret set --name JIRA_DOMAIN --vault-name ejoexamkeyvault --value ${{ secrets.JIRA_DOMAIN }} 
        - run: ansible-playbook --extra-vars="tenant=${{ secrets.ARM_TENANT_ID }} user=${{ secrets.ARM_CLIENT_ID }} secret=${{ secrets.ARM_CLIENT_SECRET }}" -i $(cat public_ip.txt)
        - run: terraform destroy -auto-approve

   

  # test_container_image:
  #   runs-on: ubuntu-latest

  #   env:
  #       JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }} 
  #       JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  #       JIRA_ACCOUNT_EMAIL: ${{ secrets.JIRA_ACCOUNT_EMAIL }}
  #       AZURE_ORGANISATION: ${{ secrets.AZURE_ORGANISATION }}
  #       AZURE_API_TOKEN: ${{ secrets.AZURE_API_TOKEN }}
  #       ZEPHYR_API_TOKEN: ${{ secrets.ZEPHYR_API_TOKEN }}
  #       EJO_GITHUB_USERNAME: ${{ secrets.EJO_GITHUB_USERNAME }}
  #       EJO_GITHUB_TOKEN: ${{ secrets.EJO_GITHUB_TOKEN }}

      
     
  #   steps:
  #     - run: echo "All your pipes are belong to me"
  #     - run: docker login -u $EJO_GITHUB_USERNAME -p $EJO_GITHUB_TOKEN ghcr.io/solidify-internal
  #     - run: docker run -dt --rm ghcr.io/solidify-internal/jtmm:latest -p zephyr -s 10006 -t N7
    

    