name: Test docker image and deploy
run-name: ${{ github.actor }} pushed 
on: [push]


jobs:
  login_to_registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.EJO_GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

  

  test_container_image:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/solidify-internal/jtmm:latest
      entrypoint: python3 -u main.py
      credentials:
        username: ${{ secrets.EJO_GITHUB_USERNAME }}
        password: ${{ secrets.EJO_GITHUB_TOKEN }}
      env:
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_ACCOUNT_EMAIL: ${{ secrets.JIRA_ACCOUNT_EMAIL }}
          AZURE_ORGANISATION: ${{ secrets.AZURE_ORGANISATION }}
          AZURE_API_TOKEN: ${{ secrets.AZURE_API_TOKEN }}
          ZEPHYR_API_TOKEN: ${{ secrets.ZEPHYR_API_TOKEN }}

      steps:
        - run: python3 -u main.py
     

    
    # steps:
    #   - uses: docker/login-action@v2
    #     with:
    #       registry: ghcr.io
    #       username: ${{ secrets.EJO_GITHUB_USERNAME }}
    #       password: ${{ secrets.EJO_GITHUB_TOKEN }}
    #   - uses: docker://ghcr.io/solidify-internal/jtmm:latest
    #     with:
    #       entrypoint: python3 -u main.py 