name: Test docker image and deploy
run-name: ${{ github.actor }} pushed 
on: [push]


jobs:
  login_to_registry:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.EJO_GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}


  deploy_migration:
      runs-on: ubuntu-latest

      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }} 
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }} 
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_ACCOUNT_EMAIL: ${{ secrets.JIRA_ACCOUNT_EMAIL }}
        AZURE_ORGANISATION: ${{ secrets.AZURE_ORGANISATION }}
        AZURE_API_TOKEN: ${{ secrets.AZURE_API_TOKEN }}
        ZEPHYR_API_TOKEN: ${{ secrets.ZEPHYR_API_TOKEN }}
        EJO_GITHUB_USERNAME: ${{ secrets.EJO_GITHUB_USERNAME }}
        EJO_GITHUB_TOKEN: ${{ secrets.EJO_GITHUB_TOKEN }}
        PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
        ANSIBLE_HOST_KEY_CHECKING: False

      steps:
        - run: az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        - run: sudo apt-get update && sudo apt-get install -y gnupg software-properties-common 
        - run: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        - run: gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
        - run: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        - run: sudo apt update
        - run: sudo apt-get install terraform python3 python3-pip
        - run: python3 -m pip install ansible
        - name: checkout repo
          uses: actions/checkout@v2.3.4
        - run: terraform init
        - run: terraform apply -auto-approve
        # - uses: Azure/login@v1
        #   with:
        #     credentials: ${{ secrets.AZURE_CREDENTIALS }}
        # - uses: Azure/get-keyvault-secrets@v1
        #   with:
        #     keyvault: "ejoexamkeyvault" # name of key vault in Azure portal
        #     secrets: 'mySecret'  # comma separated list of secret keys to fetch from key vault 
          # id: myGetSecretAction # ID for secrets that you will reference
        - run: az keyvault set-policy -n ejoexamkeyvault --secret-permissions get list set --spn ${{ secrets.APP_ID }}
        - run: az keyvault secret set --name ZEPHYR-API-TOKEN --vault-name ejoexamkeyvault --value $ZEPHYR_API_TOKEN
        - run: az keyvault secret set --name AZURE-API-TOKEN --vault-name ejoexamkeyvault --value $AZURE_API_TOKEN
        - run: az keyvault secret set --name AZURE-ORGANISATION --vault-name ejoexamkeyvault --value $AZURE_ORGANISATION
        - run: az keyvault secret set --name JIRA-ACCOUNT-EMAIL --vault-name ejoexamkeyvault --value $JIRA_ACCOUNT_EMAIL
        - run: az keyvault secret set --name JIRA-API-TOKEN --vault-name ejoexamkeyvault --value $JIRA_API_TOKEN
        - run: az keyvault secret set --name JIRA-DOMAIN --vault-name ejoexamkeyvault --value $JIRA_DOMAIN
        - run: touch private_ssh_key
        - run: echo $PRIVATE_SSH_KEY > private_ssh_key
        - run: chmod 600 private_ssh_key
        - run: ansible-playbook migration-playbook.yml -v --extra-vars="tenant=$ARM_TENANT_ID user=$ARM_CLIENT_ID secret=$ARM_CLIENT_SECRET" -i public_ip.txt --key-file "$(pwd)/private_ssh_key" --user "adminuser"
        - run: terraform destroy -auto-approve

   

  # test_container_image:
  #   runs-on: ubuntu-latest

  #   env:
        # JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }} 
        # JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        # JIRA_ACCOUNT_EMAIL: ${{ secrets.JIRA_ACCOUNT_EMAIL }}
        # AZURE_ORGANISATION: ${{ secrets.AZURE_ORGANISATION }}
        # AZURE_API_TOKEN: ${{ secrets.AZURE_API_TOKEN }}
        # ZEPHYR_API_TOKEN: ${{ secrets.ZEPHYR_API_TOKEN }}
        # EJO_GITHUB_USERNAME: ${{ secrets.EJO_GITHUB_USERNAME }}
        # EJO_GITHUB_TOKEN: ${{ secrets.EJO_GITHUB_TOKEN }}

      
     
  #   steps:
  #     - run: echo "All your pipes are belong to me"
  #     - run: docker login -u $EJO_GITHUB_USERNAME -p $EJO_GITHUB_TOKEN ghcr.io/solidify-internal
  #     - run: docker run -dt --rm ghcr.io/solidify-internal/jtmm:latest -p zephyr -s 10006 -t N7
    

    